# Generated by Django 4.0.5 on 2022-06-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
    ]
